# https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#usage
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ZcEfTEYd2hExJgBYZO8Nb6p8dFIsOGkLlKkPH9BV
          accountId: 4d5015d8cc96dd6c53ed9be950719ada
